jenkins:
   restart: always
   build: jenkins
   ports:
     - "8081:8080"
   volumes:
     - jenkins:/var/jenkins_home
   volumes_from:
     - docker
   links:
     - git
     - docker
     - registry
   environment:
     JAVA_OPTS: -Duser.timezone=America/New_York
     DOCKER_HOST: docker:2375

git:
  restart: always
  image: elsdoerfer/gitolite
  ports:
    - "2222:22"
  volumes:
    - git-repos:/home/git/repositories
    - git-ssh:/etc/ssh

docker:
  image: docker:dind
  privileged: true
  volumes:
    - dind:/var/lib/docker
  links:
    - registry
  command: --insecure-registry registry:5000

registry:
  restart: always
  image: registry:2
  ports:
   - "5000:5000"
  environment:
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
  volumes:
    - registry-data:/data
    

