jenkins:
   build: jenkins
   ports:
     - "8081:8080"
   volumes:
     - jenkins:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock
   links:
     - git


git:
  image: elsdoerfer/gitolite
  ports:
    - "2222:22"
  volumes:
    - git-repos:/home/git/repositories
    - git-ssh:/etc/ssh





   